
package com.aliyun.or.airport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QueryDataService", targetNamespace = "http://service.acdmwebservice.unionflight.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryDataService {


    /**
     * 
     * @param xmlParam
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryFlightData", targetNamespace = "http://service.acdmwebservice.unionflight.com/", className = "com.aliyun.or.airport.QueryFlightData")
    @ResponseWrapper(localName = "queryFlightDataResponse", targetNamespace = "http://service.acdmwebservice.unionflight.com/", className = "com.aliyun.or.airport.QueryFlightDataResponse")
    public String queryFlightData(
        @WebParam(name = "xmlParam", targetNamespace = "")
        String xmlParam);

}
